import type { CSSProperties } from "react";

export const sheetStyles = {
  addButton: {
    background: "#1d1f27",
    border: "1px dashed #3a3d4a",
    borderRadius: 6,
    color: "#cfd2dc",
    cursor: "pointer",
    fontSize: 12,
    padding: "6px 10px",
  },
  body: { display: "flex", flex: 1, minHeight: 0 },
  canvasArea: {
    alignItems: "flex-start",
    background: "#0d0e12",
    display: "flex",
    flex: 1,
    justifyContent: "center",
    minHeight: 0,
    minWidth: 0,
    overflow: "auto",
    padding: 16,
  },
  canvasFrame: { flexShrink: 0, lineHeight: 0, position: "relative" },
  cell: {
    border: "1px dashed #57d9a366",
    boxSizing: "border-box",
    cursor: "pointer",
    position: "absolute",
  },
  cellLabel: {
    background: "#101116cc",
    borderRadius: 2,
    color: "#d6fff0",
    fontSize: 8,
    left: 0,
    lineHeight: 1.3,
    maxWidth: "100%",
    overflow: "hidden",
    padding: "0 2px",
    position: "absolute",
    textOverflow: "ellipsis",
    top: 0,
    whiteSpace: "nowrap",
  },
  cellSelected: {
    background: "#5b8cff55",
    border: "2px solid #9bb8ff",
    boxShadow: "0 0 0 2px #5b8cff, 0 0 8px 2px #5b8cff99",
    zIndex: 2,
  },
  clearButton: {
    background: "#1d1f27",
    border: "1px solid #5a3a3a",
    borderRadius: 6,
    color: "#e0a3a3",
    cursor: "pointer",
    fontSize: 12,
    padding: "6px 10px",
  },
  detailArea: {
    background: "#0d0e12",
    borderLeft: "1px solid #2a2c36",
    display: "flex",
    flexDirection: "column",
    flexShrink: 0,
    gap: 8,
    overflow: "auto",
    padding: 16,
  },
  detailFrame: {
    border: "1px solid #2a2c36",
    flexShrink: 0,
    lineHeight: 0,
    overflow: "hidden",
    position: "relative",
  },
  detailHeader: { alignItems: "center", display: "flex", gap: 8, justifyContent: "space-between" },
  detailImage: { imageRendering: "pixelated", maxWidth: "none", position: "absolute" },
  drawPreview: {
    background: "#5b8cff22",
    border: "1px dashed #5b8cff",
    boxSizing: "border-box",
    pointerEvents: "none",
    position: "absolute",
  },
  grid: { inset: 0, pointerEvents: "none", position: "absolute" },
  gridToggle: {
    alignItems: "center",
    color: "#cfd2dc",
    display: "flex",
    fontSize: 12,
    gap: 4,
  },
  group: {
    border: "1px solid #57d9a3",
    boxShadow: "0 0 0 1px #00000088",
    boxSizing: "border-box",
    cursor: "pointer",
    position: "absolute",
  },
  groupLabel: {
    background: "#101116cc",
    bottom: 0,
    color: "#bdffe6",
    fontSize: 10,
    left: 0,
    lineHeight: 1.4,
    maxWidth: "100%",
    overflow: "hidden",
    padding: "0 3px",
    position: "absolute",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  },
  groupSelected: { border: "2px solid #5b8cff", zIndex: 2 },
  hint: { color: "#8a8d9b", fontSize: 12, padding: "0 0 8px" },
  image: { display: "block", imageRendering: "pixelated" },
  inactive: { opacity: 0.3, pointerEvents: "none" },
  listActions: { alignItems: "center", display: "flex", gap: 8 },
  overlay: { cursor: "crosshair", inset: 0, position: "absolute" },
  panel: {
    borderLeft: "1px solid #2a2c36",
    display: "flex",
    flexDirection: "column",
    gap: 12,
    minHeight: 0,
    overflowY: "auto",
    padding: 16,
    width: 320,
  },
  rect: {
    border: "1px solid #ffb27a",
    boxShadow: "0 0 0 1px #00000088",
    boxSizing: "border-box",
    cursor: "pointer",
    position: "absolute",
  },
  rectLabel: {
    background: "#101116cc",
    color: "#ffd9bd",
    fontSize: 10,
    left: 0,
    lineHeight: 1.4,
    maxWidth: "100%",
    overflow: "hidden",
    padding: "0 3px",
    position: "absolute",
    textOverflow: "ellipsis",
    top: 0,
    whiteSpace: "nowrap",
  },
  rectRow: { display: "flex", flexWrap: "wrap", gap: 8 },
  rectSelected: { border: "2px solid #5b8cff", zIndex: 1 },
  removeButton: {
    background: "transparent",
    border: "none",
    color: "#8a8d9b",
    cursor: "pointer",
    fontSize: 14,
    lineHeight: 1,
    padding: 0,
  },
  row: {
    alignItems: "center",
    background: "#1d1f27",
    border: "1px solid #2a2c36",
    borderRadius: 6,
    cursor: "pointer",
    display: "flex",
    gap: 8,
    justifyContent: "space-between",
    padding: "6px 10px",
  },
  rowAction: {
    background: "#1d1f27",
    border: "1px solid #3a3d4a",
    borderRadius: 6,
    color: "#cfd2dc",
    cursor: "pointer",
    flexShrink: 0,
    fontSize: 11,
    padding: "3px 8px",
  },
  rowActive: { border: "1px solid #5b8cff" },
  rowCount: { flexShrink: 0 },
  rowName: {
    flex: 1,
    fontSize: 13,
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  },
  rowSummary: { color: "#8a8d9b", flexShrink: 0, fontSize: 11 },
  textarea: {
    background: "#1d1f27",
    border: "1px solid #2a2c36",
    borderRadius: 6,
    color: "#e8e8ef",
    minHeight: 64,
    padding: "6px 8px",
    resize: "vertical",
  },
} satisfies Record<string, CSSProperties>;

export const inactiveStyle = (interactive: boolean): CSSProperties => {
  if (interactive) {
    return {};
  }
  return sheetStyles.inactive;
};

export const cellSelectedStyle = (selected: boolean): CSSProperties => {
  if (selected) {
    return sheetStyles.cellSelected;
  }
  return {};
};
